version: "3.7"
services:
  mongo-workspace:
    container_name: mongo-workspace
    image: mongo
    ports:
      - 27018:27017
    restart: always

  mongo-agent:
    container_name: mongo-agent
    image: mongo
    ports:
      - 27019:27017
    restart: always

  mongo-ticket:
    container_name: mongo-ticket
    image: mongo
    ports:
      - 27020:27017
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  redis-agent:
    container_name: redis-agent
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  redis-ticketing:
    container_name: redis-ticketing
    image: redis:latest
    ports:
      - 6380:6379
    restart: always

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
