version: "3.7"
services:
  mongo-inbox:
    container_name: mongo-inbox
    image: mongo
    ports:
      - 27017:27017
    restart: always

  redis-inbox:
    container_name: redis-inbox
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
